apiVersion: v1
kind: Service
metadata:
  name: movie-recommender-service
spec:
  selector:
    app: movie-recommender
  ports:
    - protocol: TCP
      port: 80          # Port inside the cluster
      targetPort: 80     # Port your container is listening on
      nodePort: 30080    # Port exposed on your local machine (NodePort)
  type: NodePort
